Sm 49 graph ql user crud
teamclairvoyant/skills-base pull request #28
Opened 2023-01-23 13:15 UTC by nivrutti1234

2023-01-24 06:17 UTC, ankit11088 requested changes
Address the comments mentioned.

2023-01-24 06:17 UTC, ankit11088 commented on ClariseMain/src/main/java/com/clairvoyant/clarise/service/impl/DefaultDesignationService.java
> +		Optional<List<Designation>> result = repository.findByIsActive(true);
Again don't hardcode.

2023-01-24 06:17 UTC, ankit11088 commented on ClariseMain/src/main/java/com/clairvoyant/clarise/service/impl/UserServiceImpl.java
> +            return Status.SUCCESS;
Either handle the exception via try-catch and try can say SUCCESS and catch can throw Exception.
If not, then don't assume..Status.SUCCESS;

2023-01-24 06:17 UTC, ankit11088 commented on ClariseMain/src/main/java/com/clairvoyant/clarise/service/impl/UserServiceImpl.java
> +            Designation designation = userDesignationMappings.stream()
findAll() for users
Get All Users > UserDesignation
			> UserRole
			> UserCategory


User {

	@OneToMany
	UserRole

	@OneToOne
	UserDesignation

	@OneToMany
	UserCategory
}

2023-01-24 06:17 UTC, ankit11088 commented on ClariseMain/src/main/java/com/clairvoyant/clarise/service/impl/UserServiceImpl.java
> +            Designation designation = userDesignationMappings.stream()
User {

	@OneToMany
	Set<UserRole>

	@OneToOne(FetchType.LAZY)
	UserDesignation

	@OneToMany
	Set<UserCategory> ;
}



UserCategory {
	@ManyToOne
	User;
}

UserRole {
	@ManyToOne
	User;
}

2023-01-25 05:27 UTC, nivrutti1234 commented on ClariseMain/src/main/java/com/clairvoyant/clarise/controller/UserController.java
> +    public UserResponseDto addOrUpdateUser(@RequestBody UserDto userDto) {
I have made changes in the UserService, so it is required to make change in the controller.

2023-01-25 06:08 UTC, ankit11088 approved these changes
Approving based on what we agreed upon.

2023-01-25 06:52 UTC, merged